#!/usr/bin/env python

from optparse import OptionParser
from twisted.internet import reactor, defer
import uuid
import random
import os.path
import socket
import datetime
import time
import sys
import urllib


import opennsa.topology
import opennsa.setup
import opennsa.nsa
import opennsa.cli.commands

TOPOLOGY_FILE = "SC2011-Topo-v5e.owl"
WSDL_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '../wsdl')
PORT = 9080


def doInfo(info_id):
    topo = opennsa.topology.parseGOLERDFTopology(TOPOLOGY_FILE)
    if ":stp:" in info_id:
        stp = topo.getSTP(info_id)
        if stp:
            print stp.urn()
            print "  network: %s" % topo.getNetwork(stp.network).name
            dest = stp.dest_stp
            if dest:
                print "  connectedTo: %s" % stp.dest_stp.urn()
    else:
        net = topo.getNetwork(info_id)
        print net.location
        for ep in net.getEndpoints():
            print "nsa.STP('%s','%s')" % (net.name,ep)
        print 80*"-"
        

def getNSA(name):
    topo = opennsa.topology.parseGOLERDFTopology(TOPOLOGY_FILE)
    for net in topo:
        if net.name == name:
            return net.nsa
        elif net.nsa.identity == name:
            return net.nsa 
        else:
            pass
    raise Exception("Could not find %s in the topology." % name)
    
@defer.inlineCallbacks
def doTerminate(terminateArgs):
    network = terminateArgs[0]
    conId = terminateArgs[1]
    client,client_nsa = createClient()
    _ = yield client.terminate(client_nsa, nsa, None, conId)
    print "Reservation terminated"


@defer.inlineCallbacks
def doQuery(queryArgs):
    nsa = queryArgs.query
    if not "http" in nsa:
        nsa = getNSA(nsa)
    client,client_nsa = createClient()
    if queryArgs.cid:
        print "Querying %s for %s" % (nsa,queryArgs.cid)
        qr = yield client.query(client_nsa, nsa, None, "Summary", connection_ids = [ queryArgs.cid ] )
    elif queryArgs.gid:
        print "Querying %s for %s" % (nsa,queryArgs.gid)
        qr = yield client.query(client_nsa, nsa, None, "Summary", global_reservation_ids = [ queryArgs.gid ] )
    else:
        print "Querying %s for %s" % (nsa,None)
        qr = yield client.query(client_nsa, nsa, None, "Summary", connection_ids = [] )
    if hasattr(qr,"reservationSummary"):
        for res in qr.reservationSummary:
            print "global-reservation-id: " + str(res.globalReservationId)
            print "description: " + str(res.description)
            print "schedule: %s -- %s" % (res.serviceParameters.schedule.startTime, res.serviceParameters.schedule.endTime)
            print "bandwidth: " + str(res.serviceParameters.bandwidth.desired)
            print "status: " + str(res.connectionState)
            if hasattr(res,"path"):
                if hasattr(res.path,"stpList"):
                    print "stplist: %s" % (res.path.stpList.stp)
                else:
                    print "stpList: " + str([res.path.sourceSTP.stpId,res.path.destSTP.stpId]) 
            print "Typeinfo: %s" % (type(res.serviceParameters.schedule.startTime))
    else:
        print qr
        

@defer.inlineCallbacks
def doReserve(options):
    topo = opennsa.topology.parseGOLERDFTopology(TOPOLOGY_FILE)
    reservation = options.reserve
    srcNet = topo.getNetwork(reservation[0])
    srcSTP = srcNet.getEndpoint(reservation[1])
    dstNet = topo.getNetwork(reservation[2])
    dstSTP = dstNet.getEndpoint(reservation[3])
    provider_nsa = srcNet.nsa
    print "Reserving (%s,%s) to (%s,%s) \n at %s (%s)" % (srcNet,srcSTP,dstNet,dstSTP, provider_nsa,provider_nsa.url())
    # Setting some defaults for now, to fill in later
    start_time=None
    end_time=None
    description='CLI Test Connection'
    # Constructing the ServiceParamaters
    if not start_time:
        start_time = datetime.datetime.utcfromtimestamp(time.time() + 120 ) # two minutes from now
    if not end_time:
        end_time   = start_time + datetime.timedelta(minutes=2) # two minutes later
    if options.gid:
        global_reservation_id = options.gid
    else:
        global_reservation_id = 'opennsa-cli:gid-%s' % random.randrange(1000,10000)
    connection_id = "urn:uuid:%s" % uuid.uuid1()
    bwp = opennsa.nsa.BandwidthParameters(1000)
    service_params  = opennsa.nsa.ServiceParameters(start_time, end_time, srcSTP, dstSTP, bandwidth=bwp)
    client,client_nsa = createClient()
    # Send the reservation and wait for response
    r = yield client.reserve(client_nsa, provider_nsa, None, global_reservation_id, description, connection_id, service_params)
    print "Reservation created.\nReservation ID: %s\nConnection ID: %s" % (global_reservation_id,connection_id)
    if r:
        urllib.urlopen("http://rembrandt0.uva.netherlight.nl:8080/register",
            urllib.urlencode({"urn": global_reservation_id,"nsa": provider_nsa.urn}))
        

@defer.inlineCallbacks
def doTerminate(options):
    nsa = options.terminate
    if not "http" in nsa:
        nsa = getNSA(nsa)
    client,client_nsa = createClient()
    print "Terminating %s at %s" % (options.cid, nsa)
    qr = yield client.terminate(client_nsa, nsa, None, "Summary", connection_ids = [ queryArgs.cid ] )
    
def createClient():
    # Constructing the client NSA
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("gmail.com",80))
    host = s.getsockname()[0]
    s.close()
    client, service, factory = opennsa.setup.createClient(host, PORT, WSDL_DIR,timeout=60)
    client_nsa = opennsa.nsa.NetworkServiceAgent('OpenNSA-commandline', 'http://%s:%s/NSI/services/ConnectionService' % (host,PORT))
    reactor.listenTCP(PORT, factory)
    return client,client_nsa

def runDefer(d):
    def handleError(x):
        x.printTraceback()
        reactor.stop()
    d.addErrback(handleError)
    d.addCallback(lambda _ : reactor.stop())
    reactor.run()

def doMain():
    parser = OptionParser()
    parser.add_option("-f", "--file", dest="filename",
                      help="write report to FILE", metavar="FILE")
    parser.add_option("-i","--info",
                        action="store",dest="info",
                        help="provide info about an id")
    parser.add_option("-r","--reserve",
                        action="store",dest="reserve",nargs=4,
                        help="make a reservation between two stps both defined by network and id")
    parser.add_option("-q","--query",
                        action="store",dest="query",
                        help="query a network about a reservation, requires network and query")
    parser.add_option("-g","--global-reservation-id",
                        action="store",dest="gid",default=None,
                        help="provide a global reservation ID for querying or reservation")
    parser.add_option("-c","--connection-id",
                        action="store",dest="cid",default=None,
                        help="provide a connection ID for querying or termination")
    parser.add_option("-t","--terminate",
                        action="store",dest="terminate",nargs=2,
                        help="terminate a reservation at a network, requires network and conn-id")
    (options, args) = parser.parse_args()

    cmd = None
    if options.gid and options.cid:
        sys.exit("Cannot use both reservation ID and connection ID")

    if options.info:
        doInfo(options.info)
    elif options.reserve:
        cmd = doReserve
        opts = options
    elif options.query:
        cmd = doQuery
        opts = options
    elif options.terminate:
        if not options.cid:
            sys.exit("Need a connection ID to terminate connections.")
        cmd = doTerminate
        opts = options
    if cmd:
        d = defer.maybeDeferred(cmd,opts)
        runDefer(d)
    


if __name__ == '__main__':
    doMain()